github.com:
    users:
        migueacastro:
            oauth_token: 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
    git_protocol: https
    oauth_token: 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
    user: migueacastro
